export const Colors = {
    primaryColor: '#1BAC4B',
    pastelGreen: '#E7F1E9',
    orange: '#FEA121',
    pink: '#FF7589',
    blue: '#3E7EFF',
    white: '#FFFFFF',
    black: '#3A3B3C',
    pastelPurple: '#DE9FFE',
    yellow: '#FE9F1A',
    grey: '#535861',
    lightGrey: '#FAFAFA',
    paleGray: '#EFEFED',
    grey_01: '#BDBDBB',
    grey_02: '#626162',
    red: '#F75555',
    green: "#1BAC4B",
    background: "#EEEEEF",
}
