export const FontSize = {
  soLarge: 36,
  large: 24,
  medium: 22,
  normal: 18,
  small: 16,
  verySmall: 14,
  tinySmall: 12,
};

export const FontFamily = {};
export const Routers = {
    Splash: "Splash",
    Main: "Main",
    Home: "Home",
    Login: "Login",
    SpecialOffers: "Special Offers",
    Recommended: "Recommended For You",
    DiscountGuaranteed: "Discount Guaranteed!",
    MyFavorite: "My Favorite",
    MoreCategory: "More Category",
    CategoryDetail: "Category Detail",
    Cart:"My Cart",
    OverView: " ",
    RatingAndReview: "Rating & Review",
    OffersAreAvailable: "Offers Are Available",
    DeliverTo: "Deliver to",
    Payment: "Payment Methods",
    TransactionHistory: "Transaction History",
    TopUp: "Top Up E-Wallet",
    EnterYourPin: "Enter Your Pin",
    CheckOut: " Checkout Orders ",
    MyFavoriteRestaurants: "My Favorite Restaurants",
    ProfileDetail: "Profile Setting",
    Address: "Address",
    Security: "Security",
    InviteFriends: "Invite Friends",
    Language: "Language",
    Profile: "Profile",
    Notification:"Notification",
    PayMethod: "Payment Method",
    HelpCenter: "Help Center",
    FAQ: "FAQ",
};

